((nil . ((ispell-local-dictionary . "pt_BR,en_US")
         (org-export-headline-levels . 5)
         (org-latex-caption-above . (image src-block table))
         (org-latex-prefer-user-labels . t)
         (org-latex-src-block-backend . minted)
         (org-ref-cite-insert-version . 2)))
 ("texto" . ((org-mode . ((bibtex-completion-bibliography . ("../refs.bib")))))))
