# -*- ispell-local-dictionary: "pt_BR"; org-export-headline-levels: 5; -*-
#+PROPERTY: header-args:js  :exports code

# header-args is needed to use src_js{} for inline source code

\todo[noline]{“Dimensions of evaluation” em inglês, talvez “dimensões de análise” ou “de verificação” seja melhor?}
* Dimensões de Avaliação

  As dimensões utilizadas neste trabalho são baseadas nas DCs. Assim usamos
  critérios estabelecidos, o que facilita a comparação de nossos resultados com
  trabalhos baseados nas DCs. O /framework/ completo possui 14 dimensões, mas os
  autores recomendam usar um subconjunto apropriado para o artefato em mãos.

  # Traduzidas diretamente de KISS 2014
  - Nível de abstração :: /Disponibilidade e tipos de mecanismos de abstração/

       O sistema fornece alguma forma de definir novos termos com a notação pra
       que eles possam ser extendidos afim de descrever ideias claramente? Os
       detalhes podem ser encapsulados? O sistema insiste em definir novos
       termos? Qual o número de novos conceitos de alto nível devem ser
       aprendidos pra se fazer uso do sistema? Eles são fáceis de aprender e
       usar?

       Cada novo conceito é um empecilho pra aprendizagem e aceitação, mas
       também pode tornar um código complexo mais compreensível.

  - Proximidade de descrição :: \todo{Traduzido de “Closeness of mapping”, poderia ser “Proximidade de mapeamento”} /Semelhança entre representação e o domínio/

       O quão relacionado é a notação com o resultado que ela descreve, ou
       melhor, o domínio do problema? Que partes parecem ser uma forma
       particularmente estranha de descrever algo?

  - Dependências ocultas :: /Vínculos importantes implícitos entre entidades/

       As dependências entre as entidades da notação são visíveis ou ocultas?
       Todas as dependências são especificadas em ambas as direções? Alterações
       locais podem ter efeitos globais confusos?

       Se uma entidade cita outra, que por sua vez cita uma terceira, a
       alteração do valor da terceira entidade pode desencadear efeitos
       inesperados. O problema chave não é o fato de A depender de B, mas sim
       que a dependência não é visível. Um caso bem conhecido de dependência
       oculta é o “problema da classe base frágil”[fn:fragile_base_class].

  - Propensão a erros :: /Notação incita erros/

       Até que ponto a notação influência o programador a cometer um erro? Fazer
       algumas coisas parece ser particularmente complexo ou difícil, p. ex.,
       juntar várias coisas?

       Em muitas linguagens dinâmicas com definições implícitas de
       variáveis[fn:var_implicit_def], um erro de tipagem em uma variável pode
       de repente levar a erros difíceis de encontrar já que o IDE nem sempre
       pode apontar tal erro devido a dinamicidade na linguagem. A inicialização
       implícita de variáveis com valor =null= pode levar a uma exceção de
       ponteiro nulo se o programador esquecer de inicializar as variáveis
       corretamente antes de usá-las.

  - Difusão         :: \todo{Diffuseness/terseness: difusão/concisão, ou dispersão} /Verbosidade da linguagem/
       # Diffuseness/terseness: difusão/concisão, ou dispersão
       Quantos símbolos ou quanto espaço a notação requer pra produzir um certo
       resultado ou expressar uma ideia. Que tipos de coisas ocupam mais espaço
       para se descrever?

  - Viscosidade     :: /Resistência a mudanças/

       Existe alguma barreira contra mudança na notação? Quanto esforço é
       necessário pra fazer uma alteração num programa expresso na notação?

       Num sistema viscoso o usuário precisa realizar várias passos para
       concluir uma tarefa. Alterar o tipo de returno de uma função pode causar
       erros em várias partes do código onde a função é chamada. Nesses casos um
       IDE pode ajudar muito.


  Outras dimensões que ficaram de fora são:

  - Comprometimento prematuro: /limitações na ordem de fazer as coisas/
  - Expressividade: /o propósito de uma entidade pode ser rapidamente determinado/
  - Consistência: /semânticas parecidas são apresentadas em estilo sintático
    parecido/
  - Operações mentais difíceis: /alto esforço cognitivo pra realizar tarefas/
  - Notação secundária: /informações extras por meio de notações além das
    formais/


  Em outras situações, e dependendo dos artefatos de informação, essas dimensões
  poderiam ser úteis. Se tivéssemos focado mais nas ferramentas e no processo de
  criação dos estudos de caso então as seguintes dimensões poderiam ser usadas:

  # progressive evaluation: análise/verificação
  # provisionality: momentaneidade, transitoriedade, provisoriedade
  - Visibilidade: /habilidade de ver os componentes claramente/
  - Análise progressiva: /trabalho realizado pode ser verificado em qualquer
    momento/
  - Provisoriedade\todo{'momentaneidade' ou 'transitoriedade'}: /grau
    de comprometimento com uma ação ou marco/


* *Revisão do JavaScript

  Talvez devêssemos colocar uma seção de revisão das ferramentas utilizadas na
  implementação dos estudos de caso? Poderíamos descrever os recursos relevantes
  para nossa análise.


* Processamento de Listas

  Uma coleção é um agrupamento com uma quantidade variável de itens, que (1)
  compartilham algum significado ao problema a se resolver e (2) precisam ser
  manipulados juntos de forma controlada.

  O único tipo de coleção no JavaScript é o arranjo, ou /array/, que pode ser
  construído através do objeto[fn:prototypes] global src_js{Array}, ou da
  notação de arranjos literais com colchetes:

  # TODO: find a way to insert a '\legend{}' before '\end{listing}' for the
  # reference. Take a look at function org-latex-src-block in ox-latex.
  #+caption: Criando coleções
  #+begin_src js
  var collection1 = new Array();
  var collection2 = [];
  #+end_src

  Uma tarefa muito comum na programação é a iteração[fn:iteration] de coleções.
  Um mecanismo muito utilizado para tal é o comando src_js{for}. Em
  \ref{code:forLoopTraverse} é demonstrado o uso do comando src_js{for} para
  percorrer os itens da coleção src_js{people} e mostrar cada um no console de
  depuração.

  #+caption: Percorrendo uma coleção com o laço src_js{for}
  #+label: code:forLoopTraverse
  #+BEGIN_SRC js
  var people = ["Alan Turing", "Alonzo Church", "Kurt Gödel"];
  var count  = 0;

  for (count = 0; count < people.length; count++) {
    console.log(people[count]);
  }
  #+END_SRC

** Formatação de preços

   Nesta seção veremos como formatar uma lista preços para serem mostrados na
   tela, p. ex., transformando um valor numérico src_js{50.45} em uma /string/
   src_js{"R$ 50.45"}. Para isso usamos uma função de formatação que é aplicada
   a cada valor da lista. A função de formatação pode ser observada em
   ref:code:formatPriceFunction.
   # Esse processo de transformação é chamado de projeção

   #+caption: Função pra formatar um preço
   #+label: code:formatPriceFunction
   #+BEGIN_SRC js
   function formatPrice(price) {
     return 'R$' + price.toFixed(2);
   }
   #+END_SRC

   Em ref:code:formatPricesFor pode-se ver a solução implementada com o laço
   src_js{for}.

   #+caption: Formatação de preços com laço src_js{for}
   #+label: code:formatPricesFor
   #+BEGIN_SRC js
   const prices = [50.45, 47, 20.99, 3.44, 1];
   let formatedPrices = [];

   for (let i = 0; i < prices.length; i++) {
     formatedPrices.push(formatPrice(prices[i]));
   }
   #+END_SRC

   Em ref:code:formatPricesMap pode-se ver a solução implementada com a função
   src_js{map}.

   #+caption: Formatação de preços com laço src_js{for}
   #+label: code:formatPricesMap
   #+BEGIN_SRC js
   const prices = [50.45, 47, 20.99, 3.44, 1];

   const formatedPrices = prices.map(formatPrice);
   #+END_SRC

   Outras ideias:

   - Adicionar $1$ a cada número de uma lista
   - Multiplicar os números de uma lista
   - Transformar palavras com letras minúsculas de uma lista em palavras com
     letras maiúsculas

** Seleção de valores com =filter()=
   Remover nomes que não começam com ‘S’

** Nivelamento de valores com =concatAll()=
** Redução de valores com ~reduce()~
** Agrupamento de valores com ~zip()~

* Coordenação de Eventos
** Contador
** Reserva de voo

* Footnotes

[fn:prototypes] Diferente da maioria das linguagens, em que objetos são
instâncias de classes, no JavaScript os objetos são extensões de /protótipos/.

[fn:iteration] O processo de percorrer, um por um, os itens de uma coleção.

[fn:var_implicit_def] Isto é, quando não se precede uma definição de variável
com =var= ou =let= por exemplo.

[fn:fragile_base_class] Veja: https://en.wikipedia.org/wiki/Fragile_base_class.
